#
# Changelog - docker-compose.yml
#
# [Initial]
# - Multi-service Docker Compose configuration for APRS system
# - USB device mapping for RTL-SDR and GPS hardware
# - Volume mounts for configuration, scripts, and persistent data
# - Environment variable configuration for easy customization
# - Network configuration for APRS-IS connectivity
# - Restart policies for reliable operation
# - Port mapping for monitoring and debugging
#
# [Purpose]
# - Orchestrates APRS receiver, transmitter, and beacon services
# - Provides hardware abstraction for different Pi configurations
# - Enables easy deployment and management of the APRS system
# - Supports development and production environments
#

version: '3.8'

services:
  # Main APRS service with Direwolf
  aprs:
    build: .
    container_name: leeds-aprs-pi
    hostname: aprs-node
    
    # Hardware device access
    devices:
      - "/dev/bus/usb:/dev/bus/usb"           # RTL-SDR USB access
      - "/dev/ttyUSB0:/dev/ttyUSB0"           # GPS dongle (if present)
      - "/dev/ttyACM0:/dev/ttyACM0"           # Alternative GPS interface
    
    # Volume mounts for configuration and data persistence
    volumes:
      - ./config:/app/config:ro               # Configuration files (read-only)
      - ./scripts:/app/scripts:ro             # Startup scripts (read-only)
      - ./logs:/app/logs:rw                   # Log files (read-write)
      - ./data:/app/data:rw                   # Persistent data storage
      - /dev/shm:/dev/shm                     # Shared memory for audio
    
    # Port mappings
    ports:
      - "14580:14580"                         # APRS-IS port
      - "8000:8000"                           # API server
      - "8001:8001"                           # Status monitoring
    
    # Environment variables - CUSTOMIZE THESE FOR YOUR STATION
    environment:
      - CALLSIGN=G0ABC                        # Your amateur radio callsign
      - APRS_PASS=12345                       # Your APRS-IS passcode
      - LAT=53.8008                           # Latitude (Leeds University default)
      - LON=-1.5491                           # Longitude (Leeds University default)
      - BEACON_MESSAGE=Leeds Space Comms APRS Node
      - BEACON_INTERVAL=600                   # Beacon every 10 minutes
      - SYMBOL_TABLE=/                        # APRS symbol table
      - SYMBOL_CODE=&                         # Gateway symbol
      - TZ=Europe/London                      # Timezone
    
    # Restart policy for reliable operation
    restart: unless-stopped
    
    # Privileged mode for hardware access
    privileged: true
    
    # Network configuration
    network_mode: host
    
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "-f", "direwolf"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web dashboard service
  dashboard:
    image: nginx:alpine
    container_name: aprs-dashboard
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - aprs
    restart: unless-stopped

  # Log aggregation service
  logmon:
    image: alpine:latest
    container_name: aprs-logmon
    volumes:
      - ./logs:/logs:ro
    command: tail -f /logs/direwolf.log
    depends_on:
      - aprs
    restart: unless-stopped

# Network configuration
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Volume definitions
volumes:
  aprs_logs:
    driver: local
  aprs_data:
    driver: local
