#
# Changelog - docker-compose.yml
#
# [Initial]
# - Multi-service Docker Compose configuration for APRS system
# - USB device mapping for RTL-SDR and GPS hardware
# - Volume mounts for configuration, scripts, and persistent data
# - Environment variable configuration for easy customization
# - Network configuration for APRS-IS connectivity
# - Restart policies for reliable operation
# - Port mapping for monitoring and debugging
#
# [Purpose]
# - Orchestrates APRS receiver, transmitter, and beacon services
# - Provides hardware abstraction for different Pi configurations
# - Enables easy deployment and management of the APRS system
# - Supports development and production environments
#

services:
  aprs:
    build: .
    container_name: leeds-aprs-pi
    privileged: true
    network_mode: host
    volumes:
      - ./config:/app/config:ro
      - ./scripts:/app/scripts:ro
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw
      - /dev/shm:/dev/shm
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      # REQUIRED: Update these with your station details
      - CALLSIGN=G0ABC                    # Your callsign
      - APRS_PASS=12345                   # APRS-IS passcode from aprs.fi
      - LAT=53.8008                       # Latitude 
      - LON=-1.5491                       # Longitude
      
      # OPTIONAL: Customize these if needed
      - BEACON_MESSAGE=Leeds APRS Pi Station
      - BEACON_INTERVAL=600               # Seconds between beacons
      - SYMBOL_TABLE=/                    # APRS symbol table
      - SYMBOL_CODE=&                     # APRS symbol code
      - TZ=Europe/London                  # Timezone
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "direwolf"]
      interval: 30s
      timeout: 10s
      retries: 3

  dashboard:
    image: nginx:alpine
    container_name: aprs-dashboard
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - aprs
    restart: unless-stopped
